-- MySQL Script generated by MySQL Workbench
-- 10/24/14 18:54:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema car
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `car` ;

-- -----------------------------------------------------
-- Table `car`.`engine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`engine` (
  `id` INT NOT NULL,
  `hpower` INT NULL,
  `torgue` INT NULL,
  `volume` INT NULL,
  `amount_of_cylynders` INT NULL,
  `fuel_type` VARCHAR(45) NULL,
  `fuel_consumption` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`interior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`interior` (
  `id` INT NOT NULL,
  `material` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `amount_of_seats` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`body`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`body` (
  `id` INT NOT NULL,
  `length` INT NULL,
  `width` INT NULL,
  `amount_of_doors` INT NULL,
  `volume_of_boot` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producer` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `class` VARCHAR(45) NULL,
  `drive` VARCHAR(45) NULL,
  `engine_id` INT NULL,
  `interior_id` INT NULL,
  `body_id` INT NULL,
  `cost` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `engine_idx` (`engine_id` ASC),
  INDEX `interior_idx` (`interior_id` ASC),
  INDEX `body_idx` (`body_id` ASC),
  CONSTRAINT `engine`
    FOREIGN KEY (`engine_id`)
    REFERENCES `car`.`engine` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `interior`
    FOREIGN KEY (`interior_id`)
    REFERENCES `car`.`interior` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `body`
    FOREIGN KEY (`body_id`)
    REFERENCES `car`.`body` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
